name: Build and Deploy Spring Boot to AKS

on:
  push:
    branches:
      - main # or your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # or your Java version

      - name: Build Spring Boot application
        run: mvn clean package -DskipTests

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry New PWD
        uses: azure/docker-login@v1
        with:
          login-server: containeregnithin.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t containeregnithin.azurecr.io/test-spring-boot-app:${{ github.sha }} .
          docker push containeregnithin.azurecr.io/test-spring-boot-app:${{ github.sha }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: resource-group-nithin-us
          cluster-name: aks-nithin-us

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy to AKS with Helm
        run: |
          helm upgrade --install spring-app-release ./helm \
            --set image.repository=containeregnithin.azurecr.io/test-spring-boot-app \
            --set image.tag=${{ github.sha }}
